apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: kube-system
  labels:
    app: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 9090
  selector:
    app: prometheus
